version: "3.9"
services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "wb_admin"
      POSTGRES_PASSWORD: "postgres"
    volumes:
#      - ./migrations/storage:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "127.0.0.1:5588:5432"
  nats-streaming:
    image: nats-streaming:0.21.0
    ports:
      - "127.0.0.1:4222:4222"